markdown: rdiscount
highlighter: null
permalink: /:year/:month/:title.html
multiviews: true
sass: true
haml: true
url: http://whinnen.com
root_desc: Whinnen.COM
paginate: 5
paginate_path: "page/:num"
post_defaults:
  layout: post
